[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[project]
name = "python-for-image-analysis"
version = "0.1.0"
description = "Image analysis in Python course"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bioio>=3.4.0",
    "black>=26.5.1",
    # "careamics>=0.3.2",
    # "cellpose>=4.2.1.1",
    "jupyter>=1.1.1",
    "jupytext>=1.19.4",
    "matplotlib>=3.11.0",
    "numpy>=2.4.6",
    "pandas>=3.0.3",
    "pre-commit>=4.6.0",
    "scikit-image>=0.26.0",
    "scipy>=1.17.1",
    "tifffile>=2026.3.3",
    "pooch>=1.9.0",
    "cmap>=0.7.2",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]


# pair solution notebooks with solution scripts only
[tool.jupytext]
formats = "solutions///ipynb,solutions///py:percent"
