[project]
name = "python-for-image-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bioio>=3.4.0",
    "black>=26.5.1",
    "careamics>=0.3.2",
    "cellpose>=4.2.1.1",
    "jupyter>=1.1.1",
    "jupytext>=1.19.4",
    "matplotlib>=3.11.0",
    "numpy>=2.4.6",
    "pandas>=3.0.3",
    "pre-commit>=4.6.0",
    "scikit-image>=0.26.0",
    "scipy>=1.17.1",
    "tifffile>=2026.3.3",
]


# pairing notebooks with scripts so that saving in jupyter saves in the script
# [tool.jupytext.formats]
# "exercises/" = "ipynb"
# "solutions/" = "py:percent"